trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  deployToProduction: true

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - script: echo 'Running tests'

- job: DeployToProd
  displayName: 'Deploy to Production'
  steps:
  - script: echo 'Deploying to production'
    condition: and(succeeded(), eq(variables['deployToProduction'], true))
